# -*- coding: utf-8 -*-
"""Copy of pandas_basic_s.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19hbRTpsanYQ7EwBp5EBYWKJqN3WkJD_l
"""

# !pip install pandas # oruvela pandas install pannalena indha command use paniti install panikalam

import numpy as np
import pandas as pd

"""Pandas = Work with tables (rows & columns) easily

Used for:

CSV / Excel data

Cleaning data

ML preprocessing

Analysis

| NumPy           | Pandas        |
| --------------- | ------------- |
| Arrays          | Tables        |
| Fast math       | Data handling |
| No column names | Column names  |
| Fixed type      | Mixed types   |
"""

# pandas use panti, table mari structures namalala manipulate panamudium ,
# columns names , rows ku names irukum

"""Series (1D – single column)

-> single column mattume irukum indha table la , idhuku peru dha series

"""

s = pd.Series([10, 20, 30])
print(s)  # orey oru column , adhula irukara elements 10,20,30 , left pakathula irukardhi column ille , index values (0, 1,2) of elements



"""2D Table

DataFrame nu soluvanga

rows and columns with column names and row names irukum

Dataframes create pandradhuku naraya ways iriki, sila pakalam ipo

1st way of creating dataframe

pudhu data use paniti dataframe create panaporom
"""

chem_df =  pd.read_csv("https://raw.githubusercontent.com/rames4498/workshop_tasks/refs/heads/master/chemistry_curated-solubility-dataset.csv")
chem_df

data = {
    "Name": ["Ram", "Sam", "Bahubali", "RRR","Samantha","Ramesh"],
    "Age": [25, 30, 22,67,89,78],
    "Salary": [50000, 60000, 45000, 99000,89000,25000]
}

# inge Name , Age , Salary moonu column names ,

#pd.DataFrame use paniti mela irukara object , oru data object table ah mathamudium
df = pd.DataFrame(data)
print(df) # inge df andradhu namaloda dataframe name

# output la oru table create ayindhirkum

import numpy as np
import pandas as pd
data = {
    "Name": ["santhanam", "Selvi", "pandi", "rama","Sam","pavi"],
    "Age": [25, 30, 22,67,89,78],
    "Salary": [50000, 60000, 45000, 99000,89000,25000]
}
df = pd.DataFrame(data)
print(df)
df.tail(3)

df.head()      # first 5 rows mattume varum

df.head(2)

df.tail()      # last 5 rows

df.tail(3) # last 3 rows

df.shape       # (rows, columns)
 # 6 rows, 3 columns

df.columns     # column names

df.info()      # data types, dataframe pathi yella information info function nala kadikum



"""2nd way of creating dataframe

pudhu data use paniti dataframe create panaporom
"""

from numpy.random import randn
np.random.seed(103)    # nama ipo random decimal values 5 rows 5 colums use paniti oru dataframe create panaporom
                       # A B C D namaloda dataframe rows peru,,,, namaloda columns peru U V W X Y
dframe=pd.DataFrame(randn(5,5),['A','B','C','D','E'],['U','V','W','X','Y'])
dframe



dframe

dframe>0     # dframe andra dataframe la values greater than zero yengalam irukardho ange true nu varum

dframe['X']>0    # X column la values greater than zero yengalam irukardho ange true nu varum

dframe[dframe['X']>0]   # X column la yengalam grater than 0 irukardho andha whole dataframe varum

dframe

dframe['X']+dframe['Y']   # rendu colums add pandrom

dframe['new'] = dframe['X']+dframe['Y'] # X  and Y columns add paniti pudhu column "new" andra perala create panitom
dframe

sherlock=dframe[dframe['U']>0]

sherlock

sherlock['X']

dframe[dframe['U']>0]['X']

dframe[dframe['U']>0][['X','Y']]

dframe.reset_index()

dframe

dframe[(dframe['U']>0) | (dframe['W']>0)]
# U column and W column rendula yedhavadhu greater than 0 irundha , andha frame output varum

dframe[(dframe['U']>0) & (dframe['W']>0)]
# U column and W column rendume greater than 0 irundha , andha frame output varum

# df andra dataframe la 50000 ku adhigama salary yaru vangurangalo kadupudikalam
df['Salary']>50000

import numpy as np
import pandas as pd
data = {
    "Name": ["santhanam", "Selvi", "pandi", "rama","Sam","pavi"],
    "Age": [25, 30, 22,67,89,78],
    "Salary": [50000, 60000, 45000, 99000,89000,25000]
}
df = pd.DataFrame(data)
print(df)
df['Age']>50

df[df['Salary']>50000]  # ivana moonu peru 50000 ku mela salary vanguranga

import numpy as np
import pandas as pd
data = {
    "Name": ["santhanam", "Selvi", "pandi", "rama","Sam","pavi"],
    "Age": [25, 30, 22,67,89,78],
    "Salary": [50000, 60000, 45000, 99000,89000,25000]
}
df = pd.DataFrame(data)
print(df)
df[df['Age']>50]

#highest salary yaru vangurangalo kanudpidukalam
df['Salary'].max()   # highest salary 99000 ,
#avangaloda peru ipo nama kandupidukanum

import numpy as np
import pandas as pd
data = {
    "Name": ["santhanam", "Selvi", "pandi", "rama","Sam","pavi"],
    "Age": [25, 30, 22,67,89,78],
    "Salary": [5000, 6000, 4000, 9000,8000,2000]
}
df = pd.DataFrame(data)
print(df)
df[df['Salary'].max() == df['Salary']]

df[df['Salary'].max() == df['Salary']] # yengalam adhigama salary match agudho , andha person oda peru age salary yellame varum

df[df['Salary'].min() == df['Salary']] # yengalam kammiana salary match agudho , andha person oda peru age salary yellame varum

# oldest person yaro kandupudikalam
df[df['Age'].max() == df['Age']]

# youngest person yaro kandupudikalam
df[df['Age'].min() == df['Age']]

import numpy as np
import pandas as pd
data = {
    "Name": ["santhanam", "Selvi", "pandi", "rama","Sam","pavi"],
    "Age": [25, 30, 22,67,89,24],
    "Salary": [3000, 6000, 3000, 9000,8000,9000]
}
df = pd.DataFrame(data)
print(df)
df[df['Salary']<5000][['Name','Age']]

data = {
    "Customer_ID": [101,102,103,104,105,106,107,108,109,110],
    "Product_Category": ["Fruits","Vegetables","Fruits","Dairy","Snacks",
                         "Dairy","Snacks","Fruits","Vegetables","Snacks"],
    "Payment_Method": ["Cash","Card","Card","Cash","UPI",
                       "UPI","Cash","Card","Cash","UPI"],
    "Quantity": [5,3,6,2,8,1,7,4,2,9],
    "Total_Bill": [250,150,300,120,400,80,350,220,130,450]
}

df = pd.DataFrame(data)
import matplotlib.pyplot as plt

df["Payment_Method"].value_counts().plot(kind="bar")

plt.title("Payment_Method Sales Count")
plt.xlabel("Method")
plt.ylabel("Number of Sales")
plt.show()